GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/242

###


POST http://localhost:3000/api/users
Content-Type: application/json

{
    "id": ,
     "firstname": "Arthan",
     "lastname": "Grindstone",
     "occupation": "Icelandic Viking",
     "age": 23
}

###

PUT http://localhost:3000/api/users/2
Content-Type: application/json

{
    "firstname": "Sara",
    "lastname": "Larsson"
}


###

DELETE http://localhost:3000/api/users/2
